# Generated by Django 4.1.7 on 2023-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
